import {
  activeUserMenuColor,
  blue,
  blueActive,
  blueHover,
  dividerGray,
  greySecondary,
  hoverUserMenuColor,
  mainBgColor,
  primaryBlack,
  red,
  redActive,
  redHover,
  shadowGrey,
  grey,
  paleGrey,
  redAccess,
} from '../constants/colors';
import {
  defaultH1,
  defaultH1Mobile,
  defaultH2,
  defaultH2Mobile,
  defaultH3,
  defaultH3Mobile,
  defaultH4,
  defaultH4Mobile,
  defaultH5,
  defaultH5Mobile,
  defaultText18,
  defaultText16,
  defaultTextSans18,
  defaultTextSans16,
  defaultTextSans12,
  defaultTextSansMed18,
  mainTextSans118,
  mainTextSans102,
  mainTextSans86,
  mainTextSans40,
  mainTextSans26,
  mainTextSans18,
  mainTextSans16,
  footerText,
} from '../constants/fontsconfigs';
import { TTheme } from '../types/styles.types';

const themeLight: TTheme = {
  primaryText: primaryBlack,
  secondaryText: greySecondary,
  markedText: blue,
  dividerColor: dividerGray,
  bgPrimary: mainBgColor,
  bgHoverUserMenu: hoverUserMenuColor,
  bgActiveUserMenu: activeUserMenuColor,
  labelColor: greySecondary,
  modalCaption: primaryBlack,
  modalText: greySecondary,
  inputField: {
    defaultBorder: dividerGray,
    borderHover: shadowGrey,
    borderActive: grey,
    disabledInput: paleGrey,
    errorColor: redAccess,
  },
  button: {
    blue: {
      default: blue,
      hover: blueHover,
      active: blueActive,
      disabled: dividerGray,
      font: mainBgColor,
    },
    red: {
      default: red,
      hover: redHover,
      active: redActive,
      disabled: dividerGray,
      font: mainBgColor,
    },
    menu: {
      default: mainBgColor,
      hover: hoverUserMenuColor,
      active: activeUserMenuColor,
      disabled: dividerGray,
      font: blue,
    },
  },
  buttonText: defaultTextSansMed18,
  firstLevelHeading: defaultH1,
  secondLevelHeading: defaultH2,
  thirdLevelHeading: defaultH3,
  fourthLevelHeading: defaultH4,
  fifthLevelHeading: defaultH5,
  firstLevelHeadingMobile: defaultH1Mobile,
  secondLevelHeadingMobile: defaultH2Mobile,
  thirdLevelHeadingMobile: defaultH3Mobile,
  fourthLevelHeadingMobile: defaultH4Mobile,
  fifthLevelHeadingMobile: defaultH5Mobile,
  labelInput: defaultTextSans16,
  text18Sans: defaultTextSans18,
  text16Sans: defaultTextSans16,
  text12Sans: defaultTextSans12,
  text18: defaultText18,
  text16: defaultText16,
  text118Sans: mainTextSans118,
  text102Sans: mainTextSans102,
  text86Sans: mainTextSans86,
  text40Sans: mainTextSans40,
  text26SubSans: mainTextSans26,
  text18SubSans: mainTextSans18,
  text16SubSans: mainTextSans16,
  footerText,
};

export default themeLight;
