import { TVocabulary } from '../types/vocabularies.types';

const en: TVocabulary = {
  headerLink: 'Main Page',
  userLogin: 'Login',
  newArticle: 'New post',
  settings: 'Settings',
  exitProfile: 'Exit',
  mainTitle: 'When I grow up',
  mainSubtitle: 'What it’s like to be a junior in a turbulent world',
  popularTags: 'Popular tags',
  popularContent: 'Popular content',
  articleEnter: 'Read More',
  freshContent: 'New content',
  comments: 'Comments',
  editArticle: 'Edit article',
  deleteArticle: 'Delete article',
  sendComment: 'Send comment',
  articleName: 'Article title',
  articleAbout: 'About',
  articleImage: 'URL of images (optional)',
  articleText: 'Article Text',
  tags: 'Tags (comma-separated)',
  saveArticle: 'Create article',
  deletepopuptext: 'By clicking «Delete Entry», the material will be removed without the possibility of recovery. ',
  subscribe: 'Subscribe',
  unsubscribe: 'Unsubscribe',
  register: 'Sign Up',
  userName: 'User Name',
  userEmail: 'Email',
  password: 'Password',
  urlImage: 'User avatar URL',
  newPassword: 'New password',
  refreshUser: 'Update settings',
  usersettings: 'Your setings',
  publishArticle: 'Publish your material',
  pageMessage: 'Page not found. To read blog, go to Home',
  publishComment: 'Post comment',
  loading: 'Please wait, loading...',
  footerMessage: 'Created by Yandex Practicum Students, Red.Types Lakers team',
  aboutUser: 'About you',
  noPageText: ' Page not found',
  goPageOnPage: 'To read the blog, go to ',
  npPageLink: 'Main',
  nickname: 'Display name',
};

export default en;
