import { TVocabulary } from '../types/vocabularies.types';

const ru: TVocabulary = {
  headerLink: 'Главная',
  userLogin: 'Войти',
  newArticle: 'Новая запись',
  settings: 'Настройки',
  exitProfile: 'Выйти',
  mainTitle: 'Когда вырасту',
  mainSubtitle: 'Каково быть джуном  в турбулентном мире',
  popularTags: 'Популярные тэги',
  popularContent: 'Популярные материалы',
  articleEnter: 'Читать дальше',
  freshContent: 'Свежие материалы',
  comments: 'Комментарии',
  editArticle: 'Редактировать запись',
  deleteArticle: 'Удалить запись',
  sendComment: 'Отправить комментарий',
  articleName: 'Название статьи',
  articleAbout: 'О чем статья',
  articleImage: 'URL изображения (опционально)',
  articleText: 'Текст статьи',
  tags: 'Теги (через запятую)',
  saveArticle: 'Сохранить запись',
  deletepopuptext: 'Нажимая кнопку «Удалить запись», материал будет удален без возможности восстановления. ',
  subscribe: 'Подписаться',
  unsubscribe: 'Отписаться',
  register: 'Зарегистрироваться',
  userName: 'Имя пользователя',
  userEmail: 'Email',
  password: 'Пароль',
  urlImage: 'URL изображения профиля',
  newPassword: 'Новый пароль',
  refreshUser: 'Обновить настройки',
  usersettings: 'Ваши настройки',
  publishArticle: 'Опубликовать запись',
  pageMessage: 'Страница не найдена. Чтобы читать блог, перейдите на Главную',
  publishComment: 'Опубликовать комментарий',
  loading: 'Подождите, данные загружаются...',
  footerMessage: 'Сделано студентами Яндекс Практикума. Команда Red.Types Lakers',
  aboutUser: 'Расскажите о себе',
  noPageText: ' Страница не найдена',
  goPageOnPage: 'Чтобы читать блог, перейдите на ',
  npPageLink: 'Главную',
  nickname: 'Отображаемое имя',
};

export default ru;
