name: "CI - Master"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: Install PM2
        run: npm i -g pm2
      - name: Run pm2 deploy
        run: |
          pm2 deploy ecosystem.config.js production
        env:
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          REF: ${{secrets.REF}}
          REPO: ${{secrets.REPO}}
          DEST_PATH: ${{secrets.DEST_PATH}}
